const SUCCESS = 'SUCCESS';
const CREATED = 'CREATED';
const NO_CONTENT = 'NO_CONTENT';
const BAD_REQUEST = 'BAD_REQUEST';
const UNAUTHORIZED = 'UNAUTHORIZED';
const NOT_FOUND = 'BOT_FOUND';

module.exports = {
  SUCCESS,
  CREATED,
  NO_CONTENT,
  BAD_REQUEST,
  UNAUTHORIZED,
  NOT_FOUND,
};