const codeHTTP = {
  SUCCESS: 'SUCCESS',
  CREATED: 'CREATED',
  NO_CONTENT: 'NO_CONTENT',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
};

module.exports = codeHTTP;
